#cloud-config
scheme_version: 1
token: <token for joiningcluster>
os:
  ssh_authorized_keys:
  - <ssh keys for rancher user>
  password: <password for console mode>
  ntp_servers:
  - 0.suse.pool.ntp.org
  - 1.suse.pool.ntp.org
install:
  mode: create
  device: /dev/sda
  iso_url: https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-amd64.iso
  tty: ttyS1,115200n8
  vip: <one of your elastic ip, can deploy if not exists but something must be set>
  vip_mode: static
  # ok for dublin m3.small.x86
  management_interface:
    interfaces:
    - name: enp1s0f0
    method: dhcp
